package com.roomwave.receiver

data class LatencyReport(val latencyMs: Double?, val rttMs: Double?, val method: String?)

/** Session-local clock mapping and a short smoothed estimate, shared by control/playback threads. */
class LatencyMeter {
    private var clockOffsetNs: Long? = null
    private var rttMs: Double? = null
    private var syncedAt = 0L
    private var measuredAt = 0L
    private var latencyMs: Double? = null
    private var method: String? = null

    @Synchronized fun sync(offsetNs: Long?, rtt: Double?, now: Long) {
        if (offsetNs == null || rtt == null || !rtt.isFinite() || rtt !in 0.0..1000.0) {
            clockOffsetNs = null; rttMs = null; latencyMs = null; method = null
            return
        }
        if (clockOffsetNs?.let { kotlin.math.abs(it.toDouble() - offsetNs) > 5_000_000 } == true) {
            latencyMs = null
        }
        clockOffsetNs = offsetNs; rttMs = rtt; syncedAt = now
    }

    @Synchronized fun record(captureNs: Long, presentationNs: Long, source: String, now: Long) {
        val offset = clockOffsetNs ?: return
        if (now - syncedAt !in 0..5_000_000_000L) return
        val value = estimateMs(captureNs, offset, presentationNs) ?: return
        val previous = latencyMs.takeIf { method == source && now - measuredAt in 0..1_500_000_000L }
        latencyMs = previous?.let { it * 0.75 + value * 0.25 } ?: value
        measuredAt = now; method = source
    }

    @Synchronized fun report(now: Long): LatencyReport {
        val synced = clockOffsetNs != null && now - syncedAt in 0..5_000_000_000L
        val fresh = synced && now - measuredAt in 0..1_500_000_000L
        return LatencyReport(if (fresh) latencyMs else null, if (synced) rttMs else null, if (fresh) method else null)
    }

    companion object {
        fun estimateMs(captureNs: Long, offsetNs: Long, presentationNs: Long): Double? {
            if (captureNs <= 0) return null // Silence generated by the host is not a measurement.
            val value = (presentationNs.toDouble() - captureNs.toDouble() - offsetNs.toDouble()) / 1_000_000.0
            return value.takeIf { it.isFinite() && it in 0.0..5000.0 }
        }
        /** AudioTrack reports a wrapping unsigned 32-bit position, even in AudioTimestamp. */
        fun unwrapPosition(raw: Long, written: Long): Long {
            val candidate = (written and -0x100000000L) or (raw and 0xffffffffL)
            return if (candidate > written) candidate - 0x100000000L else candidate
        }
        fun presentationTime(frame: Long, referenceFrame: Long, referenceNs: Long): Long =
            referenceNs + (frame - referenceFrame) * 1_000_000_000L / 48000
    }
}
